# Site settings
title: Gustavo Carvalho
email: gfcarv@gmail.com
description: "Site em constru&ccedil;&atilde;o."
baseurl: ""
url: "http://gustavocarvalho.eti.br"
github: "gfcarvalho"
twitter: "carvalhogustavo"

# Build settings
markdown: kramdown
permalink: pretty
