- menu_name: "Especialidades"

- name: "Marketing Digital"
  url: "/contato/"
  class: "services-contact"
  title: "Planejamento Estrat&eacute;gico, SEM, SEO, Social Media, Email Marketing, Web Analytics"
  
- name: "Programa&ccedil;&atilde;o para Web"
  url: "/contato/"
  class: "services-contact"
  title: "Desenvolvimento de Web Sites e Web Apps: Front-end e Back-end"
  
- name: "Consultoria e Treinamento"
  url: "/contato/"
  class: "services-contact"
  title: "Consultoria e treinamentos em TI e Marketing Digital"

#- name: "RSS"
#  url: "/feed.xml"
#  class: "rss-link"
#  title: "Subscribe to RSS"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  class: "sitemap-link"
#  title: "Sitemap for Google Webmastertools"
