- menu_name: "Servi&ccedil;os"

- name: "Marketing Digital"
  url: "/contato/"
  class: "services-contact"
  title: "Marketing Digital"
  
- name: "Programa&ccedil;&atilde;o para Web"
  url: "/contato/"
  class: "services-contact"
  title: "Programa&ccedil;&atilde;o para Web"
  
- name: "Solu&ccedil;&otilde;es em TI"
  url: "/contato/"
  class: "services-contact"
  title: "Solu&ccedil;&otilde;es em TI"

#- name: "RSS"
#  url: "/feed.xml"
#  class: "rss-link"
#  title: "Subscribe to RSS"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  class: "sitemap-link"
#  title: "Sitemap for Google Webmastertools"
